name: Run Tests with Different MongoDB Versions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Erlang/OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['23.3.4.18','24.3.4.6']
        rebar3: ['3.14.3']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: ./test/test_without_legacy_protocol.sh
